const rows = [
  {
    id: 1,
    Date: '15/01/2022',
    Project: 'Nova Form',
    client: 'Garanti',
    ProjectSoldStatus: 35,
    kickOffMeeting: 'Lorem Ipsum',
    newHireRequıred: 'Dolor sit amet, consectetur adipiscing elit.',
    projcectStartDate: '20/03/2022',
    ProjcectEndDate: '20/03/2023',
    Mail: 'lorem@ipsum.com',
  },
  {
    id: 2,
    Date: '15/01/2022',
    Project: 'Nova Form',
    client: 'Garanti',
    ProjectSoldStatus: 35,
    kickOffMeeting: 'Lorem Ipsum',
    newHireRequıred: 'Dolor sit amet, consectetur adipiscing elit.',
    projcectStartDate: '20/03/2022',
    ProjcectEndDate: '20/03/2023',
    Mail: 'lorem@ipsum.com',
  },
  {
    id: 3,
    Date: '15/01/2022',
    Project: 'Nova Form',
    client: 'Garanti',
    ProjectSoldStatus: 35,
    kickOffMeeting: 'Lorem Ipsum',
    newHireRequıred: 'Dolor sit amet, consectetur adipiscing elit.',
    projcectStartDate: '20/03/2022',
    ProjcectEndDate: '20/03/2023',
    Mail: 'lorem@ipsum.com',
  },
  {
    id: 4,
    Date: '15/01/2022',
    Project: 'Nova Form',
    client: 'Garanti',
    ProjectSoldStatus: 35,
    kickOffMeeting: 'Lorem Ipsum',
    newHireRequıred: 'Dolor sit amet, consectetur adipiscing elit.',
    projcectStartDate: '20/03/2022',
    ProjcectEndDate: '20/03/2023',
    Mail: 'lorem@ipsum.com',
  },
  {
    id: 5,
    Date: '15/01/2022',
    Project: 'Nova Form',
    client: 'Garanti',
    ProjectSoldStatus: 35,
    kickOffMeeting: 'Lorem Ipsum',
    newHireRequıred: 'Dolor sit amet, consectetur adipiscing elit.',
    projcectStartDate: '20/03/2022',
    ProjcectEndDate: '20/03/2023',
    Mail: 'lorem@ipsum.com',
  },
  {
    id: 6,
    Date: '15/01/2022',
    Project: 'Nova Form',
    client: 'Garanti',
    ProjectSoldStatus: 35,
    kickOffMeeting: 'Lorem Ipsum',
    newHireRequıred: 'Dolor sit amet, consectetur adipiscing elit.',
    projcectStartDate: '20/03/2022',
    ProjcectEndDate: '20/03/2023',
    Mail: 'lorem@ipsum.com',
  },
  {
    id: 7,
    Date: '15/01/2022',
    Project: 'Nova Form',
    client: 'Garanti',
    ProjectSoldStatus: 35,
    kickOffMeeting: 'Lorem Ipsum',
    newHireRequıred: 'Dolor sit amet, consectetur adipiscing elit.',
    projcectStartDate: '20/03/2022',
    ProjcectEndDate: '20/03/2023',
    Mail: 'lorem@ipsum.com',
  },
];

// export the rows and columns
export default rows;
